#version: "3.7"
#services:

#  mail-it:
#    build:
#      context: ./src
#    ports:
#      - "8080:8080"
#    environment:
#      - EMAIL_HOST=mailhog
#      - EMAIL_PORT=1025
#      - EMAIL_BASIC_AUTH_USER=###
#      - EMAIL_BASIC_AUTH=###
#    networks:
#        - mail-it-net

  #############################################################################################
  ###                                 MAIL HOG                                              ###
  #############################################################################################
#  mailhog:
#    image: "mailhog/mailhog"
#    ports:
#      - "8025:8025"
#      - "1025:1025"
#    networks:
#        - mail-it-net

#networks:
#  mail-it-net:
#    driver: "bridge"
