name: paybc-ci

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches_ignore:
      - master
    paths:
      - python/*.py
      - python/common/**
      - python/paybc_api/**
      - .github/workflows/paybc-ci.yml
      - trigger.txt

jobs:
  CI:
    uses: ./.github/workflows/ci-workflow.yml
    with:
      DOCKER_CONTEXT: python
      DOCKER_FILE: python/paybc_api/Dockerfile
