name: prohibition_web_app-cd

on:
  push:
    branches:
      - master
    paths:
      - web_app/**
      - .github/workflows/prohibition_web_app-cd.yml
      - trigger.txt

jobs:
  CD:
    uses: ./.github/workflows/cd-workflow.yml
    with:
      DOCKER_CONTEXT: web_app
      DOCKER_FILE: web_app/Dockerfile
      DOCKER_IMAGE_NAME: dh-prohibition-web-app
    secrets: inherit
